import { beforeEach, describe, expect, it, vi } from 'vitest'
import { NextResponse } from 'next/server'
const guard = vi.fn(), recordFind = vi.fn(), list = vi.fn(), transaction = vi.fn(), create = vi.fn(), audit = vi.fn()
const validate = vi.fn(), key = vi.fn(), write = vi.fn(), remove = vi.fn()
const lock = vi.fn()
vi.mock('@/lib/auth/require-permission', () => ({ requirePermission: (...a: unknown[]) => guard(...a) }))
vi.mock('@/lib/prisma', () => ({ prisma: { yillikTakvimKaydi: { findUnique: (...a: unknown[]) => recordFind(...a) }, yillikTakvimEk: { findMany: (...a: unknown[]) => list(...a) }, $transaction: (...a: unknown[]) => transaction(...a) } }))
vi.mock('@/lib/yillik-calisma-takvimi/storage', () => ({ validateAttachment: (...a: unknown[]) => validate(...a), createStorageKey: (...a: unknown[]) => key(...a), writeStoredFile: (...a: unknown[]) => write(...a), removeStoredFile: (...a: unknown[]) => remove(...a) }))
import { GET, POST } from './route'
const ctx = { params: Promise.resolve({ id: 'r1' }) }
const file = { name: '../../rapor.pdf', type: 'application/pdf', arrayBuffer: async () => Buffer.from('%PDF-test').buffer }
const request = { formData: vi.fn(async () => ({ get: () => file })) } as never
beforeEach(() => { vi.clearAllMocks(); lock.mockResolvedValue([{ id: 'r1', durum: 'PLANLANDI', iptalMi: false, arsivMi: false, kaynakModul: null }]); validate.mockReturnValue({ extension: '.pdf', mime: 'application/pdf', displayName: 'rapor.pdf' }); key.mockReturnValue('r1/uuid.pdf'); transaction.mockImplementation(async cb => cb({ $queryRaw: lock, yillikTakvimKaydi: { findUnique: recordFind }, yillikTakvimEk: { create }, yillikTakvimIslemGecmisi: { create: audit } })); create.mockResolvedValue({ id: 'e1', dosyaAdi: 'rapor.pdf', dosyaTuru: 'application/pdf', boyut: 9 }) })
describe('ek collection', () => {
  it('yetkisiz/view-only uploadı DB ve dosya yazmadan reddeder', async () => { guard.mockResolvedValue({ error: NextResponse.json({}, { status: 403 }) }); expect((await POST(request, ctx)).status).toBe(403); expect(write).not.toHaveBeenCalled(); expect(recordFind).not.toHaveBeenCalled() })
  it('invalid type/büyük dosyayı DB ve write öncesi reddeder', async () => { guard.mockResolvedValue({ error: null, userId: 'u1', session: { user: { permissions: [] } } }); validate.mockImplementation(() => { throw new Error('Geçersiz dosya') }); expect((await POST(request, ctx)).status).toBe(400); expect(recordFind).not.toHaveBeenCalled(); expect(write).not.toHaveBeenCalled() })
  it('iptal/arşiv kayda dosya yazmaz', async () => { guard.mockResolvedValue({ error: null, userId: 'u1', session: { user: { permissions: [] } } }); recordFind.mockResolvedValue({ id: 'r1', iptalMi: true, arsivMi: false, katilimcilar: [{ userId: 'u1' }] }); expect((await POST(request, ctx)).status).toBe(400); expect(write).not.toHaveBeenCalled() })
  it('ana sorumlu uploadında metadata ve audit tutarlı, path cevaptan gizlidir', async () => { guard.mockResolvedValue({ error: null, userId: 'u1', session: { user: { permissions: ['yilliktakvim.attachment.manage'] } } }); recordFind.mockResolvedValue({ id: 'r1', iptalMi: false, arsivMi: false, katilimcilar: [{ userId: 'u1' }] }); const response = await POST(request, ctx); expect(response.status).toBe(201); expect(write).toHaveBeenCalledWith('r1/uuid.pdf', expect.any(Buffer)); expect(audit).toHaveBeenCalledWith({ data: expect.objectContaining({ islemTuru: 'EK_YUKLE' }) }); expect(JSON.stringify(await response.json())).not.toContain('saklamaYolu') })
  it('DB/audit hatasında yazılmış dosyayı temizler', async () => { guard.mockResolvedValue({ error: null, userId: 'u1', session: { user: { permissions: ['yilliktakvim.attachment.manage'] } } }); recordFind.mockResolvedValue({ id: 'r1', iptalMi: false, arsivMi: false, katilimcilar: [{ userId: 'u1' }] }); transaction.mockRejectedValue(new Error('db')); expect((await POST(request, ctx)).status).toBe(500); expect(remove).toHaveBeenCalledWith('r1/uuid.pdf') })
  it('view ile liste saklama yolu olmadan döner', async () => { guard.mockResolvedValue({ error: null }); recordFind.mockResolvedValue({ id: 'r1' }); list.mockResolvedValue([]); const response = await GET({} as never, ctx); expect(response.status).toBe(200); expect(list.mock.calls[0][0].select).not.toHaveProperty('saklamaYolu') })
  it('lock sonrası terminal state upload metadata eklemez ve dosyayı temizler', async () => { guard.mockResolvedValue({ error: null, userId: 'u1', session: { user: { permissions: ['yilliktakvim.attachment.manage'] } } }); recordFind.mockResolvedValue({ id: 'r1', iptalMi: false, arsivMi: false, katilimcilar: [{ userId: 'u1' }] }); lock.mockResolvedValue([{ id: 'r1', durum: 'ONAYLANDI', iptalMi: false, arsivMi: false, kaynakModul: null }]); expect((await POST(request, ctx)).status).toBe(409); expect(create).not.toHaveBeenCalled(); expect(audit).not.toHaveBeenCalled(); expect(remove).toHaveBeenCalledWith('r1/uuid.pdf') })
})
