import { NextResponse } from "next/server"
import { prisma } from "@/lib/prisma"
import { requireSession } from "@/lib/auth/require-session"
import { requireUser } from "@/lib/auth/require-user"

// ISO 27001:2022 Annex A - 93 Kontrol (Türkçe açıklamalar dahil)
const ISO27001_CONTROLS = [
  // 5. Organizational controls (37 kontrol)
  { controlId: "A.5.1", categoryNumber: 5, controlNumber: 1, category: "ORGANIZATIONAL", title: "Policies for information security", titleTr: "Bilgi güvenliği politikaları", description: "Information security policy and topic-specific policies shall be defined, approved by management, published, communicated to and acknowledged by relevant personnel and relevant interested parties, and reviewed at planned intervals and if significant changes occur.", descriptionTr: "Bilgi güvenliği politikası ve konuya özgü politikalar tanımlanmalı, yönetim tarafından onaylanmalı, yayımlanmalı, ilgili personel ve ilgili taraflara iletilmeli ve kabul ettirilmeli, planlanan aralıklarla ve önemli değişiklikler olduğunda gözden geçirilmelidir." },
  { controlId: "A.5.2", categoryNumber: 5, controlNumber: 2, category: "ORGANIZATIONAL", title: "Information security roles and responsibilities", titleTr: "Bilgi güvenliği rol ve sorumlulukları", description: "Information security roles and responsibilities shall be defined and allocated according to the organization needs.", descriptionTr: "Bilgi güvenliği rol ve sorumlulukları, kuruluşun ihtiyaçlarına göre tanımlanmalı ve atanmalıdır." },
  { controlId: "A.5.3", categoryNumber: 5, controlNumber: 3, category: "ORGANIZATIONAL", title: "Segregation of duties", titleTr: "Görevlerin ayrılığı", description: "Conflicting duties and conflicting areas of responsibility shall be segregated.", descriptionTr: "Çakışan görevler ve çakışan sorumluluk alanları birbirinden ayrılmalıdır." },
  { controlId: "A.5.4", categoryNumber: 5, controlNumber: 4, category: "ORGANIZATIONAL", title: "Management responsibilities", titleTr: "Yönetim sorumlulukları", description: "Management shall require all personnel to apply information security in accordance with the established information security policy, topic-specific policies and procedures of the organization.", descriptionTr: "Yönetim, tüm personelin kuruluşun oluşturulmuş bilgi güvenliği politikası, konuya özgü politikalar ve prosedürlerine uygun olarak bilgi güvenliğini uygulamasını sağlamalıdır." },
  { controlId: "A.5.5", categoryNumber: 5, controlNumber: 5, category: "ORGANIZATIONAL", title: "Contact with authorities", titleTr: "Yetkililerle iletişim", description: "The organization shall establish and maintain contact with relevant authorities.", descriptionTr: "Kuruluş, ilgili yetkililerle iletişim kurmalı ve sürdürmelidir." },
  { controlId: "A.5.6", categoryNumber: 5, controlNumber: 6, category: "ORGANIZATIONAL", title: "Contact with special interest groups", titleTr: "Özel ilgi gruplarıyla iletişim", description: "The organization shall establish and maintain contact with special interest groups or other specialist security forums and professional associations.", descriptionTr: "Kuruluş, özel ilgi grupları veya diğer uzman güvenlik forumları ve profesyonel birliklerle iletişim kurmalı ve sürdürmelidir." },
  { controlId: "A.5.7", categoryNumber: 5, controlNumber: 7, category: "ORGANIZATIONAL", title: "Threat intelligence", titleTr: "Tehdit istihbaratı", description: "Information relating to information security threats shall be collected and analysed to produce threat intelligence.", descriptionTr: "Bilgi güvenliği tehditlerini ilişkin bilgiler, tehdit istihbaratı üretmek için toplanmalı ve analiz edilmelidir." },
  { controlId: "A.5.8", categoryNumber: 5, controlNumber: 8, category: "ORGANIZATIONAL", title: "Information security in project management", titleTr: "Proje yönetiminde bilgi güvenliği", description: "Information security shall be integrated into project management.", descriptionTr: "Bilgi güvenliği, proje yönetimine entegre edilmelidir." },
  { controlId: "A.5.9", categoryNumber: 5, controlNumber: 9, category: "ORGANIZATIONAL", title: "Inventory of information and other associated assets", titleTr: "Bilgi ve ilişkili varlıkların envanteri", description: "An inventory of information and other associated assets, including owners, shall be developed and maintained.", descriptionTr: "Sahiplerini de içeren bilgi ve ilişkili varlıkların envanteri geliştirilmeli ve sürdürülmelidir." },
  { controlId: "A.5.10", categoryNumber: 5, controlNumber: 10, category: "ORGANIZATIONAL", title: "Acceptable use of information and other associated assets", titleTr: "Bilgi ve varlıkların kabul edilebilir kullanımı", description: "Rules for the acceptable use and procedures for handling information and other associated assets shall be identified, documented and implemented.", descriptionTr: "Bilgi ve ilişkili varlıkların kabul edilebilir kullanımı için kurallar ve işleme prosedürleri belirlenmeli, dokümante edilmeli ve uygulanmalıdır." },
  { controlId: "A.5.11", categoryNumber: 5, controlNumber: 11, category: "ORGANIZATIONAL", title: "Return of assets", titleTr: "Varlıkların iadesi", description: "Personnel and other interested parties as appropriate shall return all the organization's assets in their possession upon change or termination of their employment, contract or agreement.", descriptionTr: "Personel ve diğer ilgili taraflar, istihdam, sözleşme veya anlaşmalarının değişmesi veya sona ermesi durumunda, ellerindeki tüm kuruluş varlıklarını iade etmelidir." },
  { controlId: "A.5.12", categoryNumber: 5, controlNumber: 12, category: "ORGANIZATIONAL", title: "Classification of information", titleTr: "Bilginin sınıflandırılması", description: "Information shall be classified according to the information security needs of the organization based on confidentiality, integrity, availability and relevant interested party requirements.", descriptionTr: "Bilgi, gizlilik, bütünlük, erişilebilirlik ve ilgili taraf gereksinimlerine dayalı olarak kuruluşun bilgi güvenliği ihtiyaçlarına göre sınıflandırılmalıdır." },
  { controlId: "A.5.13", categoryNumber: 5, controlNumber: 13, category: "ORGANIZATIONAL", title: "Labelling of information", titleTr: "Bilginin etiketlenmesi", description: "An appropriate set of procedures for information labelling shall be developed and implemented in accordance with the information classification scheme adopted by the organization.", descriptionTr: "Kuruluş tarafından benimsenen bilgi sınıflandırma şemasına uygun olarak bilgi etiketleme için uygun prosedürler geliştirilmeli ve uygulanmalıdır." },
  { controlId: "A.5.14", categoryNumber: 5, controlNumber: 14, category: "ORGANIZATIONAL", title: "Information transfer", titleTr: "Bilgi transferi", description: "Information transfer rules, procedures, or agreements shall be in place for all types of transfer facilities within the organization and between the organization and other parties.", descriptionTr: "Kuruluş içinde ve kuruluş ile diğer taraflar arasındaki her tür transfer olanağı için bilgi transferi kuralları, prosedürleri veya anlaşmaları mevcut olmalıdır." },
  { controlId: "A.5.15", categoryNumber: 5, controlNumber: 15, category: "ORGANIZATIONAL", title: "Access control", titleTr: "Erişim kontrolü", description: "Rules to control physical and logical access to information and other associated assets shall be established and implemented based on business and information security requirements.", descriptionTr: "Bilgi ve ilişkili varlıklara fiziksel ve mantıksal erişimi kontrol etmek için kurallar, iş ve bilgi güvenliği gereksinimlerine dayalı olarak oluşturulmalı ve uygulanmalıdır." },
  { controlId: "A.5.16", categoryNumber: 5, controlNumber: 16, category: "ORGANIZATIONAL", title: "Identity management", titleTr: "Kimlik yönetimi", description: "The full life cycle of identities shall be managed.", descriptionTr: "Kimliklerin tam yaşam döngüsü yönetilmelidir." },
  { controlId: "A.5.17", categoryNumber: 5, controlNumber: 17, category: "ORGANIZATIONAL", title: "Authentication information", titleTr: "Kimlik doğrulama bilgileri", description: "Allocation and management of authentication information shall be controlled by a management process, including advising personnel on appropriate handling of authentication information.", descriptionTr: "Kimlik doğrulama bilgilerinin tahsisi ve yönetimi, personele kimlik doğrulama bilgilerinin uygun kullanımı konusunda tavsiyeleri de içeren bir yönetim süreci ile kontrol edilmelidir." },
  { controlId: "A.5.18", categoryNumber: 5, controlNumber: 18, category: "ORGANIZATIONAL", title: "Access rights", titleTr: "Erişim hakları", description: "Access rights to information and other associated assets shall be provisioned, reviewed, modified and removed in accordance with the organization's topic-specific policy on and rules for access control.", descriptionTr: "Bilgi ve ilişkili varlıklara erişim hakları, kuruluşun erişim kontrolü konuya özgü politikası ve kurallarına uygun olarak sağlanmalı, gözden geçirilmeli, değiştirilmeli ve kaldırılmalıdır." },
  { controlId: "A.5.19", categoryNumber: 5, controlNumber: 19, category: "ORGANIZATIONAL", title: "Information security in supplier relationships", titleTr: "Tedarikçi ilişkilerinde bilgi güvenliği", description: "Processes and procedures shall be defined and implemented to manage the information security risks associated with the use of supplier's products or services.", descriptionTr: "Tedarikçi ürün veya hizmetlerinin kullanımıyla ilişkili bilgi güvenliği risklerini yönetmek için süreçler ve prosedürler tanımlanmalı ve uygulanmalıdır." },
  { controlId: "A.5.20", categoryNumber: 5, controlNumber: 20, category: "ORGANIZATIONAL", title: "Addressing information security within supplier agreements", titleTr: "Tedarikçi sözleşmelerinde bilgi güvenliği", description: "Relevant information security requirements shall be established and agreed with each supplier based on the type of supplier relationship.", descriptionTr: "İlgili bilgi güvenliği gereksinimleri, tedarikçi ilişkisinin türüne göre her tedarikçi ile oluşturulmalı ve üzerinde anlaşılmalıdır." },
  { controlId: "A.5.21", categoryNumber: 5, controlNumber: 21, category: "ORGANIZATIONAL", title: "Managing information security in the ICT supply chain", titleTr: "BİT tedarik zincirinde bilgi güvenliği yönetimi", description: "Processes and procedures shall be defined and implemented to manage the information security risks associated with the ICT products and services supply chain.", descriptionTr: "BİT ürün ve hizmetleri tedarik zinciriyle ilişkili bilgi güvenliği risklerini yönetmek için süreçler ve prosedürler tanımlanmalı ve uygulanmalıdır." },
  { controlId: "A.5.22", categoryNumber: 5, controlNumber: 22, category: "ORGANIZATIONAL", title: "Monitoring, review and change management of supplier services", titleTr: "Tedarikçi hizmetlerinin izlenmesi ve gözden geçirilmesi", description: "The organization shall regularly monitor, review, evaluate and manage change in supplier information security practices and service delivery.", descriptionTr: "Kuruluş, tedarikçi bilgi güvenliği uygulamaları ve hizmet sunumundaki değişiklikleri düzenli olarak izlemeli, gözden geçirmeli, değerlendirmeli ve yönetmelidir." },
  { controlId: "A.5.23", categoryNumber: 5, controlNumber: 23, category: "ORGANIZATIONAL", title: "Information security for use of cloud services", titleTr: "Bulut hizmetleri kullanımında bilgi güvenliği", description: "Processes for acquisition, use, management and exit from cloud services shall be established in accordance with the organization's information security requirements.", descriptionTr: "Bulut hizmetlerinin edinimi, kullanımı, yönetimi ve çıkışı için süreçler, kuruluşun bilgi güvenliği gereksinimlerine uygun olarak oluşturulmalıdır." },
  { controlId: "A.5.24", categoryNumber: 5, controlNumber: 24, category: "ORGANIZATIONAL", title: "Information security incident management planning and preparation", titleTr: "Bilgi güvenliği olay yönetimi planlama ve hazırlık", description: "The organization shall plan and prepare for managing information security incidents by defining, establishing and communicating information security incident management processes, roles and responsibilities.", descriptionTr: "Kuruluş, bilgi güvenliği olay yönetimi süreçlerini, rol ve sorumluluklarını tanımlayarak, oluşturarak ve ileterek bilgi güvenliği olaylarını yönetmeye planlamalı ve hazırlanmalıdır." },
  { controlId: "A.5.25", categoryNumber: 5, controlNumber: 25, category: "ORGANIZATIONAL", title: "Assessment and decision on information security events", titleTr: "Bilgi güvenliği olaylarının değerlendirilmesi ve karar verilmesi", description: "The organization shall assess information security events and decide if they are to be categorized as information security incidents.", descriptionTr: "Kuruluş, bilgi güvenliği olaylarını değerlendirmeli ve bunların bilgi güvenliği olayı olarak kategorize edilip edilmeyeceğine karar vermelidir." },
  { controlId: "A.5.26", categoryNumber: 5, controlNumber: 26, category: "ORGANIZATIONAL", title: "Response to information security incidents", titleTr: "Bilgi güvenliği olaylarına müdahale", description: "Information security incidents shall be responded to in accordance with the documented procedures.", descriptionTr: "Bilgi güvenliği olaylarına dokümante edilmiş prosedürlere uygun olarak müdahale edilmelidir." },
  { controlId: "A.5.27", categoryNumber: 5, controlNumber: 27, category: "ORGANIZATIONAL", title: "Learning from information security incidents", titleTr: "Bilgi güvenliği olaylarından öğrenme", description: "Knowledge gained from information security incidents shall be used to strengthen and improve the information security controls.", descriptionTr: "Bilgi güvenliği olaylarından elde edilen bilgi, bilgi güvenliği kontrollerini güçlendirmek ve iyileştirmek için kullanılmalıdır." },
  { controlId: "A.5.28", categoryNumber: 5, controlNumber: 28, category: "ORGANIZATIONAL", title: "Collection of evidence", titleTr: "Kanıt toplama", description: "The organization shall establish and implement procedures for the identification, collection, acquisition and preservation of evidence related to information security events.", descriptionTr: "Kuruluş, bilgi güvenliği olaylarıyla ilgili kanıtların belirlenmesi, toplanması, elde edilmesi ve korunması için prosedürler oluşturmalı ve uygulamalıdır." },
  { controlId: "A.5.29", categoryNumber: 5, controlNumber: 29, category: "ORGANIZATIONAL", title: "Information security during disruption", titleTr: "Kesinti sırasında bilgi güvenliği", description: "The organization shall plan how to maintain information security at an appropriate level during disruption.", descriptionTr: "Kuruluş, kesinti sırasında bilgi güvenliğini uygun bir düzeyde nasıl sürdüreceğini planlamalıdır." },
  { controlId: "A.5.30", categoryNumber: 5, controlNumber: 30, category: "ORGANIZATIONAL", title: "ICT readiness for business continuity", titleTr: "İş sürekliliği için BİT hazırlığı", description: "ICT readiness shall be planned, implemented, maintained and tested based on business continuity objectives and ICT continuity requirements.", descriptionTr: "BİT hazırlığı, iş sürekliliği hedefleri ve BİT süreklilik gereksinimlerine dayalı olarak planlanmalı, uygulanmalı, sürdürülmeli ve test edilmelidir." },
  { controlId: "A.5.31", categoryNumber: 5, controlNumber: 31, category: "ORGANIZATIONAL", title: "Legal, statutory, regulatory and contractual requirements", titleTr: "Yasal, düzenleyici ve sözleşmesel gereksinimler", description: "Legal, statutory, regulatory and contractual requirements relevant to information security and the organization's approach to meet these requirements shall be identified, documented and kept up to date.", descriptionTr: "Bilgi güvenliğiyle ilgili yasal, mevzuat, düzenleyici ve sözleşmesel gereksinimler ve kuruluşun bu gereksinimleri karşılama yaklaşımı belirlenmeli, dokümante edilmeli ve güncel tutulmalıdır." },
  { controlId: "A.5.32", categoryNumber: 5, controlNumber: 32, category: "ORGANIZATIONAL", title: "Intellectual property rights", titleTr: "Fikri mülkiyet hakları", description: "The organization shall implement appropriate procedures to protect intellectual property rights.", descriptionTr: "Kuruluş, fikri mülkiyet haklarını korumak için uygun prosedürler uygulamalıdır." },
  { controlId: "A.5.33", categoryNumber: 5, controlNumber: 33, category: "ORGANIZATIONAL", title: "Protection of records", titleTr: "Kayıtların korunması", description: "Records shall be protected from loss, destruction, falsification, unauthorized access and unauthorized release.", descriptionTr: "Kayıtlar; kayıp, imha, tahrifat, yetkisiz erişim ve yetkisiz açıklamaya karşı korunmalıdır." },
  { controlId: "A.5.34", categoryNumber: 5, controlNumber: 34, category: "ORGANIZATIONAL", title: "Privacy and protection of PII", titleTr: "Gizlilik ve KVK koruması", description: "The organization shall identify and meet the requirements regarding the preservation of privacy and protection of PII according to applicable laws and regulations and contractual requirements.", descriptionTr: "Kuruluş, yürürlükteki yasa ve düzenlemeler ile sözleşmesel gereksinimlere göre gizliliğin korunması ve kişisel verilerin korunmasına ilişkin gereksinimleri belirlenmeli ve karşılamalıdır." },
  { controlId: "A.5.35", categoryNumber: 5, controlNumber: 35, category: "ORGANIZATIONAL", title: "Independent review of information security", titleTr: "Bilgi güvenliğinin bağımsız gözden geçirilmesi", description: "The organization's approach to managing information security and its implementation including people, processes and technologies shall be reviewed independently at planned intervals, or when significant changes occur.", descriptionTr: "Kuruluşun bilgi güvenliğini yönetme yaklaşımı ve insan, süreç ve teknolojileri içeren uygulaması, planlanan aralıklarla veya önemli değişiklikler olduğunda bağımsız olarak gözden geçirilmelidir." },
  { controlId: "A.5.36", categoryNumber: 5, controlNumber: 36, category: "ORGANIZATIONAL", title: "Compliance with policies, rules and standards for information security", titleTr: "Politika ve standartlara uyumluluk", description: "Compliance with the organization's information security policy, topic-specific policies, rules and standards shall be regularly reviewed.", descriptionTr: "Kuruluşun bilgi güvenliği politikası, konuya özgü politikalar, kurallar ve standartlara uyumluluk düzenli olarak gözden geçirilmelidir." },
  { controlId: "A.5.37", categoryNumber: 5, controlNumber: 37, category: "ORGANIZATIONAL", title: "Documented operating procedures", titleTr: "Belgelenmiş işletim prosedürleri", description: "Operating procedures for information processing facilities shall be documented and made available to personnel who need them.", descriptionTr: "Bilgi işleme tesisleri için işletim prosedürleri dokümante edilmeli ve ihtiyaç duyan personele sunulmalıdır." },

  // 6. People controls (8 kontrol)
  { controlId: "A.6.1", categoryNumber: 6, controlNumber: 1, category: "PEOPLE", title: "Screening", titleTr: "Tarama", description: "Background verification checks on all candidates to become personnel shall be carried out prior to joining the organization and on an ongoing basis taking into consideration applicable laws, regulations and ethics and be proportional to the business requirements, the classification of the information to be accessed and the perceived risks.", descriptionTr: "Personel olmak için tüm adaylar üzerinde geçmiş doğrulama kontrolleri, kuruluşa katılmadan önce ve devam eden bir şekilde, yürürlükteki yasalar, düzenlemeler ve etik göz önünde bulundurularak ve iş gereksinimleri, erişilecek bilginin sınıflandırması ve algılanan risklerle orantılı olarak yapılmalıdır." },
  { controlId: "A.6.2", categoryNumber: 6, controlNumber: 2, category: "PEOPLE", title: "Terms and conditions of employment", titleTr: "İstihdam hüküm ve koşulları", description: "The employment contractual agreements shall state the personnel's and the organization's responsibilities for information security.", descriptionTr: "İstihdam sözleşmeleri, personelin ve kuruluşun bilgi güvenliği sorumluluklarını belirtmelidir." },
  { controlId: "A.6.3", categoryNumber: 6, controlNumber: 3, category: "PEOPLE", title: "Information security awareness, education and training", titleTr: "Bilgi güvenliği farkındalık eğitimi", description: "Personnel of the organization and relevant interested parties shall receive appropriate information security awareness, education and training and regular updates of the organization's information security policy, topic-specific policies and procedures, as relevant for their job function.", descriptionTr: "Kuruluş personeli ve ilgili taraflar, iş fonksiyonlarına uygun olarak uygun bilgi güvenliği farkındalık, eğitim ve öğretimi ile kuruluşun bilgi güvenliği politikası, konuya özgü politikalar ve prosedürler hakkında düzenli güncellemeler almalıdır." },
  { controlId: "A.6.4", categoryNumber: 6, controlNumber: 4, category: "PEOPLE", title: "Disciplinary process", titleTr: "Disiplin süreci", description: "A disciplinary process shall be formalized and communicated to take actions against personnel and other relevant interested parties who have committed an information security policy violation.", descriptionTr: "Bilgi güvenliği politikası ihlali gerçekleştiren personel ve diğer ilgili taraflara karşı önlem almak için disiplin süreci resmileştirilmeli ve iletilmelidir." },
  { controlId: "A.6.5", categoryNumber: 6, controlNumber: 5, category: "PEOPLE", title: "Responsibilities after termination or change of employment", titleTr: "İşten ayrılma sonrası sorumluluklar", description: "Information security responsibilities and duties that remain valid after termination or change of employment shall be defined, enforced and communicated to relevant personnel and other interested parties.", descriptionTr: "İşten ayrılma veya iş değişikliğinden sonra geçerli kalan bilgi güvenliği sorumlulukları ve görevleri tanımlanmalı, uygulanmalı ve ilgili personel ve diğer taraflara iletilmelidir." },
  { controlId: "A.6.6", categoryNumber: 6, controlNumber: 6, category: "PEOPLE", title: "Confidentiality or non-disclosure agreements", titleTr: "Gizlilik sözleşmeleri", description: "Confidentiality or non-disclosure agreements reflecting the organization's needs for the protection of information shall be identified, documented, regularly reviewed and signed by personnel and other relevant interested parties.", descriptionTr: "Kuruluşun bilgi koruma ihtiyaçlarını yansıtan gizlilik veya ifşa etmeme anlaşmaları belirlenmeli, dokümante edilmeli, düzenli olarak gözden geçirilmeli ve personel ve diğer ilgili taraflar tarafından imzalanmalıdır." },
  { controlId: "A.6.7", categoryNumber: 6, controlNumber: 7, category: "PEOPLE", title: "Remote working", titleTr: "Uzaktan çalışma", description: "Security measures shall be implemented when personnel are working remotely to protect information accessed, processed or stored outside the organization's premises.", descriptionTr: "Personel uzaktan çalışırken, kuruluşun tesisleri dışında erişilen, işlenen veya depolanan bilgiyi korumak için güvenlik önlemleri uygulanmalıdır." },
  { controlId: "A.6.8", categoryNumber: 6, controlNumber: 8, category: "PEOPLE", title: "Information security event reporting", titleTr: "Bilgi güvenliği olay bildirimi", description: "The organization shall provide a mechanism for personnel to report observed or suspected information security events through appropriate channels in a timely manner.", descriptionTr: "Kuruluş, personelin gözlemlenen veya şüphelenilen bilgi güvenliği olaylarını uygun kanallar aracılığıyla zamanında bildirmesi için bir mekanizma sağlamalıdır." },

  // 7. Physical controls (14 kontrol)
  { controlId: "A.7.1", categoryNumber: 7, controlNumber: 1, category: "PHYSICAL", title: "Physical security perimeters", titleTr: "Fiziksel güvenlik çevreleri", description: "Security perimeters shall be defined and used to protect areas that contain information and other associated assets.", descriptionTr: "Bilgi ve ilişkili varlıkları içeren alanları korumak için güvenlik çevreleri tanımlanmalı ve kullanılmalıdır." },
  { controlId: "A.7.2", categoryNumber: 7, controlNumber: 2, category: "PHYSICAL", title: "Physical entry", titleTr: "Fiziksel giriş", description: "Secure areas shall be protected by appropriate entry controls and access points.", descriptionTr: "Güvenli alanlar, uygun giriş kontrolleri ve erişim noktalarıyla korunmalıdır." },
  { controlId: "A.7.3", categoryNumber: 7, controlNumber: 3, category: "PHYSICAL", title: "Securing offices, rooms and facilities", titleTr: "Ofis, oda ve tesislerin güvenliği", description: "Physical security for offices, rooms and facilities shall be designed and implemented.", descriptionTr: "Ofis, oda ve tesisler için fiziksel güvenlik tasarlanmalı ve uygulanmalıdır." },
  { controlId: "A.7.4", categoryNumber: 7, controlNumber: 4, category: "PHYSICAL", title: "Physical security monitoring", titleTr: "Fiziksel güvenlik izleme", description: "Premises shall be continuously monitored for unauthorized physical access.", descriptionTr: "Tesisler, yetkisiz fiziksel erişim için sürekli izlenmelidir." },
  { controlId: "A.7.5", categoryNumber: 7, controlNumber: 5, category: "PHYSICAL", title: "Protecting against physical and environmental threats", titleTr: "Fiziksel ve çevresel tehditlere karşı koruma", description: "Protection against physical and environmental threats, such as natural disasters and other intentional or unintentional physical threats to infrastructure shall be designed and implemented.", descriptionTr: "Doğal afetler ve altyapıya yönelik kasıtlı veya kasıtsız fiziksel tehditler gibi fiziksel ve çevresel tehditlere karşı koruma tasarlanmalı ve uygulanmalıdır." },
  { controlId: "A.7.6", categoryNumber: 7, controlNumber: 6, category: "PHYSICAL", title: "Working in secure areas", titleTr: "Güvenli alanlarda çalışma", description: "Security measures for working in secure areas shall be designed and implemented.", descriptionTr: "Güvenli alanlarda çalışmak için güvenlik önlemleri tasarlanmalı ve uygulanmalıdır." },
  { controlId: "A.7.7", categoryNumber: 7, controlNumber: 7, category: "PHYSICAL", title: "Clear desk and clear screen", titleTr: "Temiz masa ve temiz ekran", description: "Clear desk rules for papers and removable storage media and clear screen rules for information processing facilities shall be defined and appropriately enforced.", descriptionTr: "Kağıtlar ve çıkarılabilir depolama ortamları için temiz masa kuralları ve bilgi işleme tesisleri için temiz ekran kuralları tanımlanmalı ve uygun şekilde uygulanmalıdır." },
  { controlId: "A.7.8", categoryNumber: 7, controlNumber: 8, category: "PHYSICAL", title: "Equipment siting and protection", titleTr: "Ekipman yerleşimi ve koruması", description: "Equipment shall be sited securely and protected.", descriptionTr: "Ekipman güvenli bir şekilde yerleştirilmeli ve korunmalıdır." },
  { controlId: "A.7.9", categoryNumber: 7, controlNumber: 9, category: "PHYSICAL", title: "Security of assets off-premises", titleTr: "Tesis dışı varlık güvenliği", description: "Off-site assets shall be protected.", descriptionTr: "Tesis dışı varlıklar korunmalıdır." },
  { controlId: "A.7.10", categoryNumber: 7, controlNumber: 10, category: "PHYSICAL", title: "Storage media", titleTr: "Depolama ortamları", description: "Storage media shall be managed through their life cycle of acquisition, use, transportation and disposal in accordance with the organization's classification scheme and handling requirements.", descriptionTr: "Depolama ortamları, kuruluşun sınıflandırma şeması ve kullanım gereksinimlerine uygun olarak edinme, kullanma, taşıma ve imha yaşam döngüsü boyunca yönetilmelidir." },
  { controlId: "A.7.11", categoryNumber: 7, controlNumber: 11, category: "PHYSICAL", title: "Supporting utilities", titleTr: "Destekleyici altyapı hizmetleri", description: "Information processing facilities shall be protected from power failures and other disruptions caused by failures in supporting utilities.", descriptionTr: "Bilgi işleme tesisleri, güç kesintileri ve destekleyici altyapı hizmetlerindeki arızaların neden olduğu diğer kesintilere karşı korunmalıdır." },
  { controlId: "A.7.12", categoryNumber: 7, controlNumber: 12, category: "PHYSICAL", title: "Cabling security", titleTr: "Kablo güvenliği", description: "Cables carrying power, data or supporting information services shall be protected from interception, interference or damage.", descriptionTr: "Güç, veri veya destekleyici bilgi hizmetlerini taşıyan kablolar dinleme, parazit veya hasara karşı korunmalıdır." },
  { controlId: "A.7.13", categoryNumber: 7, controlNumber: 13, category: "PHYSICAL", title: "Equipment maintenance", titleTr: "Ekipman bakımı", description: "Equipment shall be maintained correctly to ensure availability, integrity and confidentiality of information.", descriptionTr: "Ekipman, bilginin erişilebilirliği, bütünlüğü ve gizliliğini sağlamak için doğru şekilde bakılmalıdır." },
  { controlId: "A.7.14", categoryNumber: 7, controlNumber: 14, category: "PHYSICAL", title: "Secure disposal or re-use of equipment", titleTr: "Ekipmanın güvenli imhası veya yeniden kullanımı", description: "Items of equipment containing storage media shall be verified to ensure that any sensitive data and licensed software has been removed or securely overwritten prior to disposal or re-use.", descriptionTr: "Depolama ortamı içeren ekipman parçaları, imha veya yeniden kullanımdan önce hassas verilerin ve lisanslı yazılımların kaldırıldığının veya güvenli bir şekilde üzerine yazıldığının doğrulanması gerekir." },

  // 8. Technological controls (34 kontrol)
  { controlId: "A.8.1", categoryNumber: 8, controlNumber: 1, category: "TECHNOLOGICAL", title: "User endpoint devices", titleTr: "Kullanıcı uç nokta cihazları", description: "Information stored on, processed by or accessible via user endpoint devices shall be protected.", descriptionTr: "Kullanıcı uç nokta cihazlarında depolanan, işlenen veya erişilebilen bilgi korunmalıdır." },
  { controlId: "A.8.2", categoryNumber: 8, controlNumber: 2, category: "TECHNOLOGICAL", title: "Privileged access rights", titleTr: "Ayrıcalıklı erişim hakları", description: "The allocation and use of privileged access rights shall be restricted and managed.", descriptionTr: "Ayrıcalıklı erişim haklarının tahsisi ve kullanımı kısıtlanmalı ve yönetilmelidir." },
  { controlId: "A.8.3", categoryNumber: 8, controlNumber: 3, category: "TECHNOLOGICAL", title: "Information access restriction", titleTr: "Bilgi erişim kısıtlaması", description: "Access to information and other associated assets shall be restricted in accordance with the established topic-specific policy on access control.", descriptionTr: "Bilgi ve ilişkili varlıklara erişim, erişim kontrolü konuya özgü politikasına uygun olarak kısıtlanmalıdır." },
  { controlId: "A.8.4", categoryNumber: 8, controlNumber: 4, category: "TECHNOLOGICAL", title: "Access to source code", titleTr: "Kaynak koda erişim", description: "Read and write access to source code, development tools and software libraries shall be appropriately managed.", descriptionTr: "Kaynak kod, geliştirme araçları ve yazılım kütüphanelerine okuma ve yazma erişimi uygun şekilde yönetilmelidir." },
  { controlId: "A.8.5", categoryNumber: 8, controlNumber: 5, category: "TECHNOLOGICAL", title: "Secure authentication", titleTr: "Güvenli kimlik doğrulama", description: "Secure authentication technologies and procedures shall be implemented based on information access restrictions and the topic-specific policy on access control.", descriptionTr: "Güvenli kimlik doğrulama teknolojileri ve prosedürleri, bilgi erişim kısıtlamaları ve erişim kontrolü konuya özgü politikasına dayalı olarak uygulanmalıdır." },
  { controlId: "A.8.6", categoryNumber: 8, controlNumber: 6, category: "TECHNOLOGICAL", title: "Capacity management", titleTr: "Kapasite yönetimi", description: "The use of resources shall be monitored and adjusted in line with current and expected capacity requirements.", descriptionTr: "Kaynakların kullanımı izlenmeli ve mevcut ve beklenen kapasite gereksinimlerine göre ayarlanmalıdır." },
  { controlId: "A.8.7", categoryNumber: 8, controlNumber: 7, category: "TECHNOLOGICAL", title: "Protection against malware", titleTr: "Zararlı yazılımlara karşı koruma", description: "Protection against malware shall be implemented and supported by appropriate user awareness.", descriptionTr: "Zararlı yazılımlara karşı koruma uygulanmalı ve uygun kullanıcı farkındalığı ile desteklenmelidir." },
  { controlId: "A.8.8", categoryNumber: 8, controlNumber: 8, category: "TECHNOLOGICAL", title: "Management of technical vulnerabilities", titleTr: "Teknik açıklık yönetimi", description: "Information about technical vulnerabilities of information systems in use shall be obtained, the organization's exposure to such vulnerabilities shall be evaluated and appropriate measures shall be taken.", descriptionTr: "Kullanımdaki bilgi sistemlerinin teknik açıklıkları hakkında bilgi edinilmeli, kuruluşun bu açıklıklara maruziyeti değerlendirilmeli ve uygun önlemler alınmalıdır." },
  { controlId: "A.8.9", categoryNumber: 8, controlNumber: 9, category: "TECHNOLOGICAL", title: "Configuration management", titleTr: "Konfigürasyon yönetimi", description: "Configurations, including security configurations, of hardware, software, services and networks shall be established, documented, implemented, monitored and reviewed.", descriptionTr: "Donanım, yazılım, hizmetler ve ağların güvenlik yapılandırmaları dahil yapılandırmaları oluşturulmalı, dokümante edilmeli, uygulanmalı, izlenmeli ve gözden geçirilmelidir." },
  { controlId: "A.8.10", categoryNumber: 8, controlNumber: 10, category: "TECHNOLOGICAL", title: "Information deletion", titleTr: "Bilgi silme", description: "Information stored in information systems, devices or in any other storage media shall be deleted when no longer required.", descriptionTr: "Bilgi sistemlerinde, cihazlarda veya diğer depolama ortamlarında saklanan bilgi, artık gerekli olmadığında silinmelidir." },
  { controlId: "A.8.11", categoryNumber: 8, controlNumber: 11, category: "TECHNOLOGICAL", title: "Data masking", titleTr: "Veri maskeleme", description: "Data masking shall be used in accordance with the organization's topic-specific policy on access control and other related topic-specific policies, and business requirements, taking applicable legislation into consideration.", descriptionTr: "Veri maskeleme, kuruluşun erişim kontrolü konuya özgü politikası ve diğer ilgili politikalar ile iş gereksinimleri ve yürürlükteki mevzuat dikkate alınarak kullanılmalıdır." },
  { controlId: "A.8.12", categoryNumber: 8, controlNumber: 12, category: "TECHNOLOGICAL", title: "Data leakage prevention", titleTr: "Veri sızıntısı önleme", description: "Data leakage prevention measures shall be applied to systems, networks and any other devices that process, store or transmit sensitive information.", descriptionTr: "Veri sızıntısı önleme tedbirleri, hassas bilgiyi işleyen, depolayan veya ileten sistemlere, ağlara ve diğer cihazlara uygulanmalıdır." },
  { controlId: "A.8.13", categoryNumber: 8, controlNumber: 13, category: "TECHNOLOGICAL", title: "Information backup", titleTr: "Bilgi yedekleme", description: "Backup copies of information, software and systems shall be maintained and regularly tested in accordance with the agreed topic-specific policy on backup.", descriptionTr: "Bilgi, yazılım ve sistemlerin yedek kopyaları, yedekleme konuya özgü politikasına uygun olarak muhafaza edilmeli ve düzenli olarak test edilmelidir." },
  { controlId: "A.8.14", categoryNumber: 8, controlNumber: 14, category: "TECHNOLOGICAL", title: "Redundancy of information processing facilities", titleTr: "Bilgi işleme tesislerinin yedekliliği", description: "Information processing facilities shall be implemented with redundancy sufficient to meet availability requirements.", descriptionTr: "Bilgi işleme tesisleri, erişilebilirlik gereksinimlerini karşılamak için yeterli yedeklilik ile uygulanmalıdır." },
  { controlId: "A.8.15", categoryNumber: 8, controlNumber: 15, category: "TECHNOLOGICAL", title: "Logging", titleTr: "Günlük kayıtları", description: "Logs that record activities, exceptions, faults and other relevant events shall be produced, stored, protected and analysed.", descriptionTr: "Aktiviteleri, istisnaları, hataları ve diğer ilgili olayları kaydeden günlükler üretilmeli, depolanmalı, korunmalı ve analiz edilmelidir." },
  { controlId: "A.8.16", categoryNumber: 8, controlNumber: 16, category: "TECHNOLOGICAL", title: "Monitoring activities", titleTr: "İzleme faaliyetleri", description: "Networks, systems and applications shall be monitored for anomalous behaviour and appropriate actions taken to evaluate potential information security incidents.", descriptionTr: "Ağlar, sistemler ve uygulamalar anormal davranışlar için izlenmeli ve potansiyel bilgi güvenliği olaylarını değerlendirmek için uygun önlemler alınmalıdır." },
  { controlId: "A.8.17", categoryNumber: 8, controlNumber: 17, category: "TECHNOLOGICAL", title: "Clock synchronization", titleTr: "Saat senkronizasyonu", description: "The clocks of information processing systems used by the organization shall be synchronized to approved time sources.", descriptionTr: "Kuruluş tarafından kullanılan bilgi işleme sistemlerinin saatleri, onaylı zaman kaynaklarına senkronize edilmelidir." },
  { controlId: "A.8.18", categoryNumber: 8, controlNumber: 18, category: "TECHNOLOGICAL", title: "Use of privileged utility programs", titleTr: "Ayrıcalıklı yardımcı programların kullanımı", description: "The use of utility programs that can be capable of overriding system and application controls shall be restricted and tightly controlled.", descriptionTr: "Sistem ve uygulama kontrollerini geçersiz kılabilen yardımcı programların kullanımı kısıtlanmalı ve sıkı şekilde kontrol edilmelidir." },
  { controlId: "A.8.19", categoryNumber: 8, controlNumber: 19, category: "TECHNOLOGICAL", title: "Installation of software on operational systems", titleTr: "İşletim sistemlerine yazılım kurulumu", description: "Procedures and measures shall be implemented to securely manage software installation on operational systems.", descriptionTr: "İşletim sistemlerine yazılım kurulumunu güvenli bir şekilde yönetmek için prosedürler ve önlemler uygulanmalıdır." },
  { controlId: "A.8.20", categoryNumber: 8, controlNumber: 20, category: "TECHNOLOGICAL", title: "Networks security", titleTr: "Ağ güvenliği", description: "Networks and network devices shall be secured, managed and controlled to protect information in systems and applications.", descriptionTr: "Sistemler ve uygulamalardaki bilgiyi korumak için ağlar ve ağ cihazları güvenli hale getirilmeli, yönetilmeli ve kontrol edilmelidir." },
  { controlId: "A.8.21", categoryNumber: 8, controlNumber: 21, category: "TECHNOLOGICAL", title: "Security of network services", titleTr: "Ağ hizmetleri güvenliği", description: "Security mechanisms, service levels and service requirements of network services shall be identified, implemented and monitored.", descriptionTr: "Ağ hizmetlerinin güvenlik mekanizmaları, hizmet seviyeleri ve hizmet gereksinimleri belirlenmeli, uygulanmalı ve izlenmelidir." },
  { controlId: "A.8.22", categoryNumber: 8, controlNumber: 22, category: "TECHNOLOGICAL", title: "Segregation of networks", titleTr: "Ağ ayrımı", description: "Groups of information services, users and information systems shall be segregated in the organization's networks.", descriptionTr: "Bilgi hizmetleri, kullanıcılar ve bilgi sistemleri grupları kuruluşun ağlarında ayrılmalıdır." },
  { controlId: "A.8.23", categoryNumber: 8, controlNumber: 23, category: "TECHNOLOGICAL", title: "Web filtering", titleTr: "Web filtreleme", description: "Access to external websites shall be managed to reduce exposure to malicious content.", descriptionTr: "Zararlı içeriğe maruziyeti azaltmak için dış web sitelerine erişim yönetilmelidir." },
  { controlId: "A.8.24", categoryNumber: 8, controlNumber: 24, category: "TECHNOLOGICAL", title: "Use of cryptography", titleTr: "Kriptografi kullanımı", description: "Rules for the effective use of cryptography, including cryptographic key management, shall be defined and implemented.", descriptionTr: "Kriptografik anahtar yönetimi dahil olmak üzere kriptografinin etkin kullanımı için kurallar tanımlanmalı ve uygulanmalıdır." },
  { controlId: "A.8.25", categoryNumber: 8, controlNumber: 25, category: "TECHNOLOGICAL", title: "Secure development life cycle", titleTr: "Güvenli geliştirme yaşam döngüsü", description: "Rules for the secure development of software and systems shall be established and applied.", descriptionTr: "Yazılım ve sistemlerin güvenli geliştirilmesi için kurallar oluşturulmalı ve uygulanmalıdır." },
  { controlId: "A.8.26", categoryNumber: 8, controlNumber: 26, category: "TECHNOLOGICAL", title: "Application security requirements", titleTr: "Uygulama güvenliği gereksinimleri", description: "Information security requirements shall be identified, specified and approved when developing or acquiring applications.", descriptionTr: "Uygulamalar geliştirilirken veya edinilirken bilgi güvenliği gereksinimleri belirlenmeli, tanımlanmalı ve onaylanmalıdır." },
  { controlId: "A.8.27", categoryNumber: 8, controlNumber: 27, category: "TECHNOLOGICAL", title: "Secure system architecture and engineering principles", titleTr: "Güvenli sistem mimarisi ve mühendislik ilkeleri", description: "Principles for engineering secure systems shall be established, documented, maintained and applied to any information system development activities.", descriptionTr: "Güvenli sistemler mühendisliği ilkeleri oluşturulmalı, dokümante edilmeli, sürdürülmeli ve herhangi bir bilgi sistemi geliştirme faaliyetine uygulanmalıdır." },
  { controlId: "A.8.28", categoryNumber: 8, controlNumber: 28, category: "TECHNOLOGICAL", title: "Secure coding", titleTr: "Güvenli kodlama", description: "Secure coding principles shall be applied to software development.", descriptionTr: "Güvenli kodlama ilkeleri yazılım geliştirmeye uygulanmalıdır." },
  { controlId: "A.8.29", categoryNumber: 8, controlNumber: 29, category: "TECHNOLOGICAL", title: "Security testing in development and acceptance", titleTr: "Geliştirme ve kabul testlerinde güvenlik", description: "Security testing processes shall be defined and implemented in the development life cycle.", descriptionTr: "Güvenlik test süreçleri geliştirme yaşam döngüsünde tanımlanmalı ve uygulanmalıdır." },
  { controlId: "A.8.30", categoryNumber: 8, controlNumber: 30, category: "TECHNOLOGICAL", title: "Outsourced development", titleTr: "Dış kaynaklı geliştirme", description: "The organization shall direct, monitor and review the activities related to outsourced system development.", descriptionTr: "Kuruluş, dış kaynaklı sistem geliştirme ile ilgili faaliyetleri yönlendirmeli, izlemeli ve gözden geçirmelidir." },
  { controlId: "A.8.31", categoryNumber: 8, controlNumber: 31, category: "TECHNOLOGICAL", title: "Separation of development, test and production environments", titleTr: "Geliştirme, test ve üretim ortamlarının ayrılması", description: "Development, testing and production environments shall be separated and secured.", descriptionTr: "Geliştirme, test ve üretim ortamları ayrılmalı ve güvenlik altına alınmalıdır." },
  { controlId: "A.8.32", categoryNumber: 8, controlNumber: 32, category: "TECHNOLOGICAL", title: "Change management", titleTr: "Değişiklik yönetimi", description: "Changes to information processing facilities and information systems shall be subject to change management procedures.", descriptionTr: "Bilgi işleme tesisleri ve bilgi sistemlerindeki değişiklikler, değişiklik yönetimi prosedürlerine tabi olmalıdır." },
  { controlId: "A.8.33", categoryNumber: 8, controlNumber: 33, category: "TECHNOLOGICAL", title: "Test information", titleTr: "Test bilgileri", description: "Test information shall be appropriately selected, protected and managed.", descriptionTr: "Test bilgileri uygun şekilde seçilmeli, korunmalı ve yönetilmelidir." },
  { controlId: "A.8.34", categoryNumber: 8, controlNumber: 34, category: "TECHNOLOGICAL", title: "Protection of information systems during audit testing", titleTr: "Denetim testleri sırasında bilgi sistemlerinin korunması", description: "Audit tests and other assurance activities involving assessment of operational systems shall be planned and agreed between the tester and appropriate management.", descriptionTr: "İşletim sistemlerinin değerlendirmesini içeren denetim testleri ve diğer güvence faaliyetleri, test eden ve uygun yönetim arasında planlanmalı ve üzerinde anlaşılmalıdır." },
]

// 93 kontrolü seed et
export async function POST() {
  try {
    // PR-Y2.5-iso27001-A: requireUser → user.role
    const { user, error } = await requireUser()
    if (error) return error

    // Sadece ADMIN veya IT_MANAGER yapabilir
    if (!["ADMIN", "SUPER_ADMIN", "IT_MANAGER"].includes(user.role)) {
      return NextResponse.json({ error: "Bu islemi yapmaya yetkiniz yok" }, { status: 403 })
    }

    // Mevcut kontrol sayısını kontrol et
    const existingCount = await prisma.iso27001Control.count()
    if (existingCount > 0) {
      return NextResponse.json({
        success: false,
        message: `Veritabaninda zaten ${existingCount} kontrol mevcut. Seed islemi atlanıyor.`,
        existingCount,
      })
    }

    // Kontrol sayısı doğrulama
    if (ISO27001_CONTROLS.length !== 93) {
      return NextResponse.json({
        error: `Kontrol sayisi hatali: ${ISO27001_CONTROLS.length} (beklenen: 93)`,
      }, { status: 500 })
    }

    // Kontrolleri ekle
    const result = await prisma.iso27001Control.createMany({
      data: ISO27001_CONTROLS.map(c => ({
        controlId: c.controlId,
        title: c.title,
        titleTr: c.titleTr,
        description: c.description,
        descriptionTr: c.descriptionTr,
        category: c.category as any,
        categoryNumber: c.categoryNumber,
        controlNumber: c.controlNumber,
        status: "NOT_APPLICABLE",
        applicability: true,
      })),
    })

    // Eklenen sayı doğrulama
    if (result.count !== 93) {
      return NextResponse.json({
        success: false,
        message: `Beklenenden farkli sayida kontrol eklendi: ${result.count}/93`,
        count: result.count,
      })
    }

    return NextResponse.json({
      success: true,
      message: `${result.count} kontrol basariyla eklendi`,
      count: result.count,
    })
  } catch (error) {
    console.error("Seed hatasi:", error)
    return NextResponse.json(
      { error: "Kontroller eklenemedi" },
      { status: 500 }
    )
  }
}

// Kontrol sayısını getir
export async function GET() {
  try {
    // PR-Y2.5-iso27001-A: requireSession
    const { error } = await requireSession()
    if (error) return error

    const count = await prisma.iso27001Control.count()
    return NextResponse.json({ count, expected: 93 })
  } catch (error) {
    return NextResponse.json({ error: "Sayim yapilamadi" }, { status: 500 })
  }
}
