import { beforeEach, describe, expect, it, vi } from 'vitest'
import { NextRequest, NextResponse } from 'next/server'
const guard = vi.fn(), itemFind = vi.fn(), userFind = vi.fn(), transaction = vi.fn(), update = vi.fn(), remove = vi.fn(), audit = vi.fn()
const lock = vi.fn()
vi.mock('@/lib/auth/require-permission', () => ({ requirePermission: (...a: unknown[]) => guard(...a) }))
vi.mock('@/lib/prisma', () => ({ prisma: { yillikTakvimChecklist: { findFirst: (...a: unknown[]) => itemFind(...a) }, user: { findFirst: (...a: unknown[]) => userFind(...a) }, $transaction: (...a: unknown[]) => transaction(...a) } }))
import { DELETE, PATCH } from './route'
const ctx = { params: Promise.resolve({ id: 'r1', checklistId: 'c1' }) }
const request = (method: string, body?: unknown) => new NextRequest('http://local/item', { method, ...(body && { body: JSON.stringify(body), headers: { 'content-type': 'application/json' } }) })
const item = { id: 'c1', kayitId: 'r1', sorumluId: 'assigned', kanitGerekli: false, tamamlandi: false, kayit: { iptalMi: false, arsivMi: false, katilimcilar: [{ userId: 'owner' }], _count: { ekler: 0 } } }
beforeEach(() => { vi.clearAllMocks(); lock.mockResolvedValue([{ id: 'r1', durum: 'PLANLANDI', iptalMi: false, arsivMi: false, kaynakModul: null }]); transaction.mockImplementation(async cb => cb({ $queryRaw: lock, yillikTakvimChecklist: { findFirst: itemFind, update, delete: remove }, yillikTakvimIslemGecmisi: { create: audit } })); update.mockResolvedValue(item) })
describe('checklist item', () => {
  it('yetkisiz mutationda DB yok', async () => { guard.mockResolvedValue({ error: NextResponse.json({}, { status: 403 }) }); expect((await PATCH(request('PATCH', { tamamlandi: true }), ctx)).status).toBe(403); expect(itemFind).not.toHaveBeenCalled() })
  it('atanmış sorumlu yalnız tamamlanma aksiyonunu yapabilir', async () => { guard.mockResolvedValue({ error: null, userId: 'assigned', session: { user: { permissions: ['yilliktakvim.edit'] } } }); itemFind.mockResolvedValue(item); expect((await PATCH(request('PATCH', { tamamlandi: true }), ctx)).status).toBe(200); expect(update).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ tamamlayanId: 'assigned' }) })) })
  it('atanmış sorumlu yapısal alanı değiştiremez', async () => { guard.mockResolvedValue({ error: null, userId: 'assigned', session: { user: { permissions: ['yilliktakvim.edit'] } } }); itemFind.mockResolvedValue(item); expect((await PATCH(request('PATCH', { baslik: 'Yeni' }), ctx)).status).toBe(403) })
  it('kanıt gereken maddeyi ek yokken tamamlatmaz', async () => { guard.mockResolvedValue({ error: null, userId: 'owner', session: { user: { permissions: ['yilliktakvim.edit'] } } }); itemFind.mockResolvedValue({ ...item, kanitGerekli: true }); expect((await PATCH(request('PATCH', { tamamlandi: true }), ctx)).status).toBe(400); expect(transaction).not.toHaveBeenCalled() })
  it('olmayan item 404; iptal/arşiv mutation 400', async () => { guard.mockResolvedValue({ error: null, userId: 'owner', session: { user: { permissions: ['yilliktakvim.edit'] } } }); itemFind.mockResolvedValueOnce(null); expect((await DELETE(request('DELETE'), ctx)).status).toBe(404); itemFind.mockResolvedValueOnce({ ...item, kayit: { ...item.kayit, arsivMi: true } }); expect((await DELETE(request('DELETE'), ctx)).status).toBe(400) })
  it('ana sorumlu silme ve audit aynı transactiondadır', async () => { guard.mockResolvedValue({ error: null, userId: 'owner', session: { user: { permissions: ['yilliktakvim.edit'] } } }); itemFind.mockResolvedValue(item); expect((await DELETE(request('DELETE'), ctx)).status).toBe(200); expect(remove).toHaveBeenCalledWith({ where: { id: 'c1' } }); expect(audit).toHaveBeenCalledWith({ data: expect.objectContaining({ islemTuru: 'CHECKLIST_SIL' }) }) })
  it('lock sonrası terminal state checklist mutationlarını 409 ile reddeder', async () => { guard.mockResolvedValue({ error: null, userId: 'owner', session: { user: { permissions: ['yilliktakvim.edit'] } } }); itemFind.mockResolvedValue(item); lock.mockResolvedValue([{ id: 'r1', durum: 'ONAYLANDI', iptalMi: false, arsivMi: false, kaynakModul: null }]); expect((await PATCH(request('PATCH', { baslik: 'Yeni' }), ctx)).status).toBe(409); expect(update).not.toHaveBeenCalled(); expect(audit).not.toHaveBeenCalled(); expect((await DELETE(request('DELETE'), ctx)).status).toBe(409); expect(remove).not.toHaveBeenCalled() })
})
