import { PERMISSION_KEYS } from '@/lib/auth/permissions'

/** Salt-okunur production sayfası ve GET API için kabul edilen izinler. */
export const YILLIK_TAKVIM_VIEW_PERMISSIONS = [
  PERMISSION_KEYS.YILLIK_TAKVIM_VIEW,
  PERMISSION_KEYS.YILLIK_TAKVIM_ADMIN,
] as const

/** Yeni kayıt oluşturma için view'dan bağımsız izinler. */
export const YILLIK_TAKVIM_CREATE_PERMISSIONS = [
  PERMISSION_KEYS.YILLIK_TAKVIM_CREATE,
  PERMISSION_KEYS.YILLIK_TAKVIM_ADMIN,
] as const

/** Kayıt düzenleme için view/create'dan bağımsız izinler. */
export const YILLIK_TAKVIM_EDIT_PERMISSIONS = [
  PERMISSION_KEYS.YILLIK_TAKVIM_EDIT,
  PERMISSION_KEYS.YILLIK_TAKVIM_ADMIN,
] as const

/** Kayıt iptali için view/create/edit'ten bağımsız izinler. */
export const YILLIK_TAKVIM_CANCEL_PERMISSIONS = [
  PERMISSION_KEYS.YILLIK_TAKVIM_CANCEL,
  PERMISSION_KEYS.YILLIK_TAKVIM_ADMIN,
] as const

export const YILLIK_TAKVIM_COMPLETE_PERMISSIONS = [
  PERMISSION_KEYS.YILLIK_TAKVIM_COMPLETE,
  PERMISSION_KEYS.YILLIK_TAKVIM_ADMIN,
] as const

export const YILLIK_TAKVIM_APPROVE_PERMISSIONS = [
  PERMISSION_KEYS.YILLIK_TAKVIM_APPROVE,
  PERMISSION_KEYS.YILLIK_TAKVIM_ADMIN,
] as const

export const YILLIK_TAKVIM_ATTACHMENT_PERMISSIONS = [
  PERMISSION_KEYS.YILLIK_TAKVIM_ATTACHMENT_MANAGE,
  PERMISSION_KEYS.YILLIK_TAKVIM_ADMIN,
] as const

export const YILLIK_TAKVIM_NOTIFICATION_PERMISSIONS = [
  PERMISSION_KEYS.YILLIK_TAKVIM_NOTIFICATION_MANAGE,
  PERMISSION_KEYS.YILLIK_TAKVIM_ADMIN,
] as const
